# Generated by Django 3.2.3 on 2021-05-23 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_id', models.CharField(max_length=100)),
                ('numb', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Roomtype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('people', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('D', 'Desocupada'), ('O', 'Ocupada')], default='D', max_length=1)),
                ('description', models.TextField()),
                ('image_header', models.ImageField(default='rooms/None/no-img.jpg', upload_to='rooms/')),
                ('url', models.SlugField(max_length=255, unique=True)),
                ('roomtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('state', models.CharField(choices=[('E', 'Espera'), ('T', 'Tomada'), ('C', 'Cancelada')], default='E', max_length=1)),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room')),
            ],
        ),
    ]
