# Generated by Django 3.2.3 on 2021-05-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='checkin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkout',
            field=models.DateTimeField(),
        ),
    ]
